import 'package:flutter/material.dart';

const primaryColor = Colors.white;
const secondaryColor = Colors.grey;
const secondaryGreen = Color.fromRGBO(67, 96,  201, 1);
const primaryGreen = Color.fromRGBO(67, 96,  201, 1);
const fontColorGrey = Color(0xfff505050);
const fontColorGrey2 = Color(0xfffF4F4F4);
const colorStart = Color.fromRGBO(67, 96,  201, 1);
const colorIconGrey = Color(0xfffBFC2C8);
const primaryOrange = Color(0xfffE94834);
const greyTextPaySuccess = Color(0xfff868686);
const textSmall_SemiBold = TextStyle(color: Colors.black,fontSize: 13,fontWeight: FontWeight.w600);
const textMedium_Grey13 = TextStyle(color: Colors.black38,fontSize: 13);
const testLarge_SemiBold28 = TextStyle(color: Colors.black,fontSize: 28,fontWeight:FontWeight.w600);
const textMedium_Bold15 = TextStyle(color: Colors.black,fontSize: 15,fontWeight: FontWeight.bold);
const textMedium_Medium18 = TextStyle(color:Colors.black,fontSize: 18,fontWeight: FontWeight.w500);
const ColorSlibarHomeMain = Color(0xfffFEF0EE);
const primaryBlue = Color.fromRGBO(67, 96,  201, 1);
const primaryYellow = Color.fromRGBO(255, 228, 181, 1 );
const inputBox = Color.fromRGBO(242, 242,  242, 1);
